import {StyleSheet, Dimensions} from 'react-native';
import {BaseColor} from '@config';
import * as Utils from '@utils';
import {BaseSetting} from '../../config/setting';

export default StyleSheet.create({
  imageBackground: {
    height: 36,
    width: 36 * 2.24,
    alignSelf: 'center',
  },
  absHeader: {
    position: 'absolute',
    top: 0,
    width: '100%',
    left: 0,
    elevation: 11,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.26,
    shadowRadius: 4.68,
  },
  absHeaderBlur: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  searchForm: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: 'center',
    width: '100%',
  },
  contentServiceIcon: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  contentCartPromotion: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  btnPromotion: {
    height: 25,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  contentHiking: {
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 10,
  },
  promotionBanner: {
    height: Utils.scaleWithPixel(100),
    width: '100%',
    marginTop: 10,
  },
  line: {
    height: 1,
    backgroundColor: BaseColor.textSecondaryColor,
    marginTop: 10,
    marginBottom: 20,
  },
  iconContent: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: BaseColor.fieldColor,
  },
  itemService: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingTop: 10,
  },
  promotionItem: {
    borderRadius: 8,
    width: Utils.scaleWithPixel(200),
    height: Utils.scaleWithPixel(250),
  },
  tourItem: {
    borderRadius: 8,
    width: Utils.scaleWithPixel(135),
    height: Utils.scaleWithPixel(160),
  },
  img: {
    width: 44,
    height: 44,
    borderRadius: 22,
    resizeMode: 'contain',
  },
  gridListContainer: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    height: 60,
    width: 60,
    borderRadius: 30,
    overflow: 'hidden',
    backgroundColor: BaseColor.primaryColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBoxContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 10,
  },
  filterIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 50,
  },
  mapView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignContent: 'flex-end',
    width: BaseSetting.deviceWidth,
    height: BaseSetting.deviceHeight - 100,
    borderRadius: 13,
    // marginVertical: 20,
  },
  markerCallout: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 10,
  },
  previewImgStyle: {
    width: '100%',
    height: Utils.scaleWithPixel(150),
    resizeMode: 'cover',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  previewNameWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // flex: 1,
  },
  sizeWrapper: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: BaseColor.whiteColor,
    padding: 5,
    borderRadius: 5,
  },
  rateWrapper: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    backgroundColor: BaseColor.whiteColor,
    padding: 5,
    borderRadius: 5,
  },
  sizeText: {
    fontSize: 12,
    color: BaseColor.primaryColor,
  },
  offerImg: {
    position: 'absolute',
    top: 0,
    left: 10,
    height: 25,
    width: 25,
  },
  closeWrapper: {
    position: 'absolute',
    top: 7,
    right: 7,
    height: 22,
    width: 22,
    borderRadius: 11,
    backgroundColor: BaseColor.whiteColor,
    justifyContent: 'center',
    alignItems: 'center',
    // padding: 5,
  },
  inputWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearInput: {
    backgroundColor: '#ccc',
    height: 20,
    width: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    right: 30,
    position: 'absolute',
    top: 12,
  },
  animationWrap: {
    height: Dimensions.get('window').height / 2,
    width: Dimensions.get('window').width,
    // backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  },
  animation: {
    height: 150,
    width: 200,
  },
  rightBigIcon: {
    height: 42,
    width: 40,
    margin: 0,
    padding: 0,
    borderRadius: 8,
  },
  filtersWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    padding: 6,
    borderRadius: 12,
    backgroundColor: '#EEE',
  },
  filterValue: {
    borderRadius: 8,
    marginRight: 6,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    height: 46,
  },
  filterBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  filterValueLabel: {
    fontSize: 10,
    color: '#999',
    paddingBottom: 2,
  },
  filterValueText: {
    fontSize: 12,
  },
  searchIcon: {
    backgroundColor: BaseColor.primaryColor,
    borderRadius: 8,
    height: 46,
    width: 40,
    marginLeft: 5,
  },
  searchInput: {
    height: 46,
    flex: 1,
  },
  customRefreshControl: {
    position: 'absolute',
    top: 250,
    width: 40,
    zIndex: 1,
    left: '50%',
    marginLeft: -20,
  },
  animationWrap1: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
  },
  animation1: {
    width: 270,
    height: 270,
  },
  scrollTopWrapper: {
    position: 'absolute',
    bottom: 70,
    right: 20,
    height: 50,
    width: 50,
    borderRadius: 25,
    backgroundColor: BaseColor.primaryColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
